# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReferralPlease' do
  #Pod for M1 chip
   post_install do |installer|
     installer.pods_project.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
     end
   end
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReferralPlease
  pod 'Firebase/Analytics'
  pod 'FirebaseUI'
  pod 'Firebase/Firestore'
  pod 'SDWebImage', :modular_headers => true

  target 'ReferralPleaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReferralPleaseUITests' do
    # Pods for testing
  end

end
